# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0

# Joint limits: https://emanual.robotis.com/docs/en/dxl/mx/mx-64/#control-table
# Wheel Mode 	both are 0
# Joint Mode 	neither are 0
# Multi-turn Mode 	both are 4095

left_jaw:
  ID: 12
  Return_Delay_Time: 0
  Operating_Mode: 3
#  Profile_Acceleration: 0
#  Profile_Velocity: 0
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 0
right_jaw:
  ID: 13
  Return_Delay_Time: 0
  Operating_Mode: 3
#  Profile_Acceleration: 0
#  Profile_Velocity: 0
#  CW_Angle_Limit: 0
#  CCW_Angle_Limit: 0

